service: chatbot-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    NODE_ENV: ${self:provider.stage}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}

functions:
  chat:
    handler: src/handlers/chat.handler
    timeout: 30
    events:
      - http:
          path: /api/chat
          method: post
          cors: true
      - http:
          path: /api/chat
          method: options
          cors: true

  health:
    handler: src/handlers/health.handler
    timeout: 10
    events:
      - http:
          path: /api/health
          method: get
          cors: true

plugins:
  - serverless-dotenv-plugin   
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3001
    host: localhost
    cors: true
    printOutput: true